---
###################
# NTP Time Server #
###################
- name: NTP - regedit - Synchronize with an external time source
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\W32Time\Parameters
    name: Type
    data: NTP
    type: string
  tags: NTP_TIME

- name: NTP - regedit - Set AnnounceFlags
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\W32Time\Config
    name: AnnounceFlags
    data: 5
    type: dword
  tags: NTP_TIME

- name: NTP - regedit - Enable
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpServer
    name: Enabled
    data: 1
    type: dword
  tags: NTP_TIME

- name: NTP - regedit - Specify time sources
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\W32Time\Parameters
    name: NtpServer
    data: 1.pool.ntp.org,0x1
    type: string
  tags: NTP_TIME

- name: NTP - regedit - Set MaxPosPhaseCorrection
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\W32Time\Config
    name: MaxNegPhaseCorrection
    data: 708
    type: dword
  tags: NTP_TIME

- name: NTP - Service w32time restart
  win_service:
    name: w32time
    state: restarted
  tags: NTP_TIME
