---
##########
# Ubuntu #
##########

# Command Build Tool Packages
Build_Tool_Packages:
  - apt-transport-https
  - autoconf
  - bison                         # OpenJ9
  - build-essential
  - ca-certificates
  - cpio
  - curl
  - flex                          # Openj9
  - g++
  - gcc
  - gettext
  - git
  - libasound2-dev
  - libcups2-dev
  - libcurl4-openssl-dev
  - libdwarf-dev                  # OpenJ9
  - libelf-dev
  - libexpat1-dev
  - libffi-dev
  - libfreetype6-dev
  - libfontconfig1-dev
  - libgmp3-dev
  - libmpfr-dev
  - libmpfr-doc
  - libssl-dev
  - libwww-perl
  - make
  - ntp
  - openjdk-8-jdk
  - pigz
  - pkg-config
  - systemtap-sdt-dev
  - wget
  - zip

OpenJFX_Build_Tool_Packages:
  - gperf

gcc_compiler:
  - g++-4.8
  - gcc-4.8

Additional_Packages_Ubuntu16:
  - xserver-xorg-legacy                 # Not actually sure if this is still needed
  - libgstreamer0.10-dev                # OpenJFX prereq
  - libgstreamer-plugins-base0.10-dev   # OpenJFX prereq
  - libmpfr4
  - libmpfr4-dbg

Additional_Packages_Ubuntu18:
  - libgstreamer1.0-dev

Additional_Build_Tools_x86:
  - libnuma-dev
  - numactl
  - gcc-7
  - g++-7
  - gcc-multilib                        # a dependency required for executing a 32-bit C binary

Additional_Build_Tools_ppc64le:
  - libnuma-dev
  - numactl
  - gcc-7                         # OpenJ9
  - g++-7                         # OpenJ9

Additional_Build_Tools_s390x:
  - gcc-7                         # OpenJ9
  - g++-7                         # OpenJ9
  - numactl
  - libfreetype6-dev              # Needed by test state=installed

Additional_Build_Tools_aarch64:
  - libpng-dev

Additional_Build_Tools_Ubuntu20:
  - cmake
  - ccache

Test_Tool_Packages:
  - acl
  - mercurial
  - perl
  - xauth
  - xorg
  - xvfb
  - binfmt-support
  - qemu-user-static
  - unzip
  - libexpat1-dev
  - libcurl4-openssl-dev
  - fakeroot

Test_Tool_Packages_x86_64:
  - pulseaudio
